# This Dockerfile is pre-processed by the ./utils/docker script, it is not meant to be used directly.

FROM ./server/ AS server
FROM ./client/ AS client
FROM ./utils/xorg-deps/ AS xorg-deps
FROM ./runtime/$RUNTIME_DOCKERFILE AS runtime

# tells glass-fence which version of the API to use
LABEL net.arxndev.glass-fence.api-version=3
LABEL net.arxndev.glass-fence.maintainer="ARXNDEV"
LABEL net.arxndev.glass-fence.description="AI-Powered Remote Browser Isolation Platform"

COPY --from=server /src/bin/plugins/ /etc/glass-fence/plugins/
COPY --from=server /src/bin/glass-fence /usr/bin/glass-fence
COPY --from=client /src/dist/ /var/www
COPY --from=xorg-deps /usr/local/lib/xorg/modules/drivers/dummy_drv.so /usr/lib/xorg/modules/drivers/dummy_drv.so
COPY --from=xorg-deps /usr/local/lib/xorg/modules/input/gf_drv.so /usr/lib/xorg/modules/input/gf_drv.so
COPY config.yml /etc/glass-fence/glass-fence.yaml

COPY apps/docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
