services:
  firefox:
    image: "arxndevv/glass-fence/firefox:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8081:8080"
      - "53001:53001/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@60
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_UDPMUX: 53001
      NEKO_WEBRTC_ICELITE: 1
      NEKO_WEBRTC_NAT1TO1: 127.0.0.1
      NEKO_CAPTURE_VIDEO_IDS: main
      NEKO_CAPTURE_VIDEO_CODEC: vp8

  chromium:
    image: "arxndevv/glass-fence/chromium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8082:8080"
      - "53002:53002/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@60
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_UDPMUX: 53002
      NEKO_WEBRTC_ICELITE: 1
      NEKO_WEBRTC_NAT1TO1: 127.0.0.1
      NEKO_CAPTURE_VIDEO_IDS: main
      NEKO_CAPTURE_VIDEO_CODEC: vp8



  linux:
    image: "arxndevv/glass-fence/xfce:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8084:8080"
      - "53004:53004/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@60
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_UDPMUX: 53004
      NEKO_WEBRTC_ICELITE: 1
      NEKO_WEBRTC_NAT1TO1: 127.0.0.1
      NEKO_CAPTURE_VIDEO_IDS: main
      NEKO_CAPTURE_VIDEO_CODEC: vp8
