#!/bin/bash
cd "$(dirname "$0")"

if [ "$(docker images -q glass-fence_server:src 2> /dev/null)" == "" ]; then
    echo "Image 'glass-fence_server:src' not found. Run ./build first."
    exit 1
fi

docker run -it \
    --name "glass-fence_server_go" \
    --entrypoint="go" \
    -v "${PWD}/../:/src" \
    glass-fence_server:src "$@";
#
# copy package files
docker cp glass-fence_server_go:/src/go.mod "../go.mod"
docker cp glass-fence_server_go:/src/go.sum "../go.sum"

#
# commit changes to image
docker commit "glass-fence_server_go" "glass-fence_server"

#
# remove contianer
docker rm "glass-fence_server_go"
