#!/bin/bash
cd "$(dirname "$0")"

#
# aborting if any command returns a non-zero value
set -e

#
# build server
docker run --rm -it \
    -v "${PWD}/../:/src" \
    --entrypoint="/bin/bash" \
    glass-fence_server:src "./build" "$@";

#
# remove old plugins
docker exec glass-fence_server_dev rm -rf /etc/glass-fence/plugins

#
# replace server binary in container
docker cp "${PWD}/../bin/glass-fence" glass-fence_server_dev:/usr/bin/glass-fence

#
# replace plugin binaries in container
if [ -d "${PWD}/../bin/plugins" ];
then
    docker cp "${PWD}/../bin/plugins" glass-fence_server_dev:/etc/glass-fence/plugins
fi

#
# restart server
docker exec glass-fence_server_dev supervisorctl -c /etc/glass-fence/supervisord.conf restart glass-fence
