#!/bin/bash
cd "$(dirname "$0")"

if [ -z "$(docker images -q glass-fence_server:app 2> /dev/null)" ]; then
    echo "Image 'glass-fence_server:app' not found. Running ./build first."
    ./build
fi

if [ -z $GF_PORT ]; then
    GF_PORT="3000"
fi

if [ -z $GF_MUX ]; then
    GF_MUX="52100"
fi

if [ -z $GF_NAT1TO1 ]; then
    for i in $(ifconfig -l 2>/dev/null); do
        GF_NAT1TO1=$(ipconfig getifaddr $i)
        if [ ! -z $GF_NAT1TO1 ]; then
            break
        fi
    done

    if [ -z $GF_NAT1TO1 ]; then
        GF_NAT1TO1=$(hostname -I 2>/dev/null | awk '{print $1}')
    fi

    if [ -z $GF_NAT1TO1 ]; then
        GF_NAT1TO1=$(hostname -i 2>/dev/null)
    fi
fi

# if first argument is nvidia, start with nvidia runtime
if [ "$1" = "nvidia" ]; then
    echo "Starting nvidia docker image"
    EXTRAOPTS="--gpus all"
    CONFIG="config.nvidia.yml"
elif [ "$1" = "intel" ]; then
    echo "Starting intel docker image"
    EXTRAOPTS="--device /dev/dri"
    # TODO: add intel config
    # CONFIG="config.intel.yml"
else
    echo "Starting default docker image"
    EXTRAOPTS=""
    CONFIG="config.yml"
fi

echo "Using app port: ${GF_PORT}"
echo "Using mux port: ${GF_MUX}"
echo "Using IP address: ${GF_NAT1TO1}"

# start server
docker run --rm -it \
    --name "glass-fence_server_dev" \
    -p "${GF_PORT}:8080" \
    -p "${GF_MUX}:${GF_MUX}/tcp" \
    -p "${GF_MUX}:${GF_MUX}/udp" \
    -e "GF_WEBRTC_UDPMUX=${GF_MUX}" \
    -e "GF_WEBRTC_TCPMUX=${GF_MUX}" \
    -e "GF_WEBRTC_NAT1TO1=${GF_NAT1TO1}" \
    -e "GF_SESSION_FILE=/home/glassfence/sessions.txt" \
    -v "${PWD}/runtime/$CONFIG:/etc/glass-fence/glass-fence.yml" \
    -e "GF_DEBUG=1" \
    --shm-size=2G \
    --security-opt seccomp=unconfined \
    $EXTRAOPTS \
    glass-fence_server:app;
